CI-492: Make it possible for administrators to change the logo in the code
wahanegi/vibereport pull request #123
Opened 2023-07-24 07:24 UTC by SerhiiBorozenets

2023-07-24 08:05 UTC, rogergraves requested changes
@SerhiiBorozenets in order for logo changing to work on Heroku [we would need to add an additional service](https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted-from-the-application) to Heroku. I think this is too much trouble and ongoing costs since the logo is going to be set only once, when the project is instantiated. Please hard-code the logo into the project and change the README instructions for swapping out the logo it via code instead of ActiveAdmin.

2023-07-24 08:59 UTC, SBorozenets approved these changes

2023-07-24 10:16 UTC, rogergraves commented on README.md
> +For example, if the original logo is logo.svg, your new logo should also be named logo.svg and replace the existing file.
Please replace the text here with something very specific instructions. For example:

"Save your company logo as logo.svg, and then copy over the current image in app/assets/images/logo.svg. The width to height ratio of your logo should be set to X:Y". -- please adjust to whatever the ratio is (4:3, 16:9, etc.)

2023-07-24 10:16 UTC, rogergraves commented on README.md
> +Remove the existing favicon file from the assets folder and replace it with your new favicon file, again making sure to name it favicon.svg.
Suggestion:
"Copy your company's favicon (in SVG format) to  app/assets/images/favicon.svg. It should be a square image (1:1 ratio)."

2023-07-24 10:16 UTC, rogergraves commented on README.md
> +Depending on the technology stack of your application, you might need to build or compile your project to incorporate the new logo and favicon. Once the build is successful, deploy your application t
This copy is not useful and might be confusing, so please remove it.

2023-07-28 17:15 UTC, rogergraves approved these changes

2023-07-31 07:28 UTC, merged