[Snyk] Fix for 2 vulnerabilities
wahanegi/vibereport pull request #150
Opened 2023-08-24 08:14 UTC by rogergraves

<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to fix one or more vulnerable packages in the `rubygems` dependencies of this project.</h3>

#### Changes included in this PR

- Changes to the following files to upgrade the vulnerable dependencies to a fixed version:
    - Gemfile
    - Gemfile.lock

#### Vulnerabilities that will be fixed
##### With an upgrade:
Severity                   | Priority Score (*)                   | Issue                   | Breaking Change                   | Exploit Maturity
:-------------------------:|-------------------------|:-------------------------|:-------------------------|:-------------------------
![medium severity](https://res.cloudinary.com/snyk/image/upload/w_20,h_20/v1561977819/icon/m.png "medium severity")  |  **501/1000**  <br/> **Why?** Recently disclosed, Has a fix available, CVSS 4.3  | Information Exposure <br/>[SNYK-RUBY-ACTIVESUPPORT-5851458](https://snyk.io/vuln/SNYK-RUBY-ACTIVESUPPORT-5851458) |  No  | No Known Exploit 
![medium severity](https://res.cloudinary.com/snyk/image/upload/w_20,h_20/v1561977819/icon/m.png "medium severity")  |  **501/1000**  <br/> **Why?** Recently disclosed, Has a fix available, CVSS 4.3  | Information Exposure <br/>[SNYK-RUBY-RAILTIES-5851410](https://snyk.io/vuln/SNYK-RUBY-RAILTIES-5851410) |  No  | No Known Exploit 

(*) Note that the real score may have changed since the PR was raised.

Check the changes in this PR to ensure they won't cause issues with your project.

------------

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open fix PRs.*

For more information:  <img src="https://api.segment.io/v1/pixel/track?data=eyJ3cml0ZUtleSI6InJyWmxZcEdHY2RyTHZsb0lYd0dUcVg4WkFRTnNCOUEwIiwiYW5vbnltb3VzSWQiOiJmYzYxYzcwNi02YzY0LTQxMTAtOTI3OS03ZTQxYzM3NzZjMjkiLCJldmVudCI6IlBSIHZpZXdlZCIsInByb3BlcnRpZXMiOnsicHJJZCI6ImZjNjFjNzA2LTZjNjQtNDExMC05Mjc5LTdlNDFjMzc3NmMyOSJ9fQ==" width="0" height="0"/>
🧐 [View latest project report](https://app.snyk.io/org/rogergraves/project/6998e670-d362-4fcf-a4ad-ddff8c06149d?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;fix-pr)

🛠 [Adjust project settings](https://app.snyk.io/org/rogergraves/project/6998e670-d362-4fcf-a4ad-ddff8c06149d?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;fix-pr/settings)

📚 [Read more about Snyk's upgrade and patch logic](https://support.snyk.io/hc/en-us/articles/360003891078-Snyk-patches-to-fix-vulnerabilities)

[//]: # (snyk:metadata:{"prId":"fc61c706-6c64-4110-9279-7e41c3776c29","prPublicId":"fc61c706-6c64-4110-9279-7e41c3776c29","dependencies":[{"name":"activeadmin","from":"2.13.1","to":"2.14.0"},{"name":"cssbundling-rails","from":"1.1.2","to":"1.2.0"},{"name":"groupdate","from":"6.2.1","to":"6.3.0"},{"name":"jsbundling-rails","from":"1.1.1","to":"1.1.2"},{"name":"passwordless","from":"0.11.0","to":"0.12.0"},{"name":"rails","from":"7.0.4.3","to":"7.0.7.1"},{"name":"rspec-rails","from":"6.0.2","to":"6.0.3"},{"name":"rubocop-rails","from":"2.19.1","to":"2.20.0"}],"packageManager":"rubygems","projectPublicId":"6998e670-d362-4fcf-a4ad-ddff8c06149d","projectUrl":"https://app.snyk.io/org/rogergraves/project/6998e670-d362-4fcf-a4ad-ddff8c06149d?utm_source=github&utm_medium=referral&page=fix-pr","type":"auto","patch":[],"vulns":["SNYK-RUBY-ACTIVESUPPORT-5851458","SNYK-RUBY-RAILTIES-5851410"],"upgrade":["SNYK-RUBY-ACTIVESUPPORT-5851458","SNYK-RUBY-RAILTIES-5851410"],"isBreakingChange":false,"env":"prod","prType":"fix","templateVariants":["priorityScore"],"priorityScoreList":[501,501],"remediationStrategy":"vuln"})

---

**Learn how to fix vulnerabilities with free interactive lessons:**

 🦉 [Learn about vulnerability in an interactive lesson of Snyk Learn.](https://learn.snyk.io/?loc&#x3D;fix-pr)

2023-10-25 17:52 UTC, SerhiiBorozenets requested changes

2023-10-25 17:52 UTC, SerhiiBorozenets commented on db/schema.rb
> +  end
@LyubovP this table has been removed earlier (db/migrate/20230901084529_remove_passwordless_table.rb)

2023-10-25 18:05 UTC, LyubovP commented
[like]  Liubov Pidoshva reacted to your message:
________________________________
From: SerhiiBorozenets ***@***.***>
Sent: Wednesday, October 25, 2023 5:52:51 PM
To: wahanegi/vibereport ***@***.***>
Cc: Liubov Pidoshva ***@***.***>; Mention ***@***.***>
Subject: Re: [wahanegi/vibereport] [Snyk] Fix for 2 vulnerabilities (PR #150)


@SerhiiBorozenets requested changes on this pull request.

________________________________

In db/schema.rb<https://github.com/wahanegi/vibereport/pull/150#discussion_r1372123526>:

> +  create_table "passwordless_sessions", force: :cascade do |t|
+    t.bigint "authenticatable_id"
+    t.string "authenticatable_type"
+    t.datetime "claimed_at", precision: nil
+    t.datetime "created_at", precision: nil, null: false
+    t.datetime "expires_at", precision: nil, null: false
+    t.string "remote_addr", null: false
+    t.datetime "timeout_at", precision: nil, null: false
+    t.string "token", null: false
+    t.datetime "updated_at", precision: nil, null: false
+    t.text "user_agent", null: false
+    t.index ["authenticatable_type", "authenticatable_id"], name: "authenticatable"
+  end


@LyubovP<https://github.com/LyubovP> this table has been removed earlier (db/migrate/20230901084529_remove_passwordless_table.rb)

—
Reply to this email directly, view it on GitHub<https://github.com/wahanegi/vibereport/pull/150#pullrequestreview-1697937956>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AUGHY4UPQXFW3JQVPSAFTZTYBFGXHAVCNFSM6AAAAAA34T6A5WVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMOJXHEZTOOJVGY>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-10-30 10:40 UTC, SerhiiBorozenets commented on Gemfile.lock
> -  x86_64-darwin-22
@LyubovP please don't remove these lines, it needs for other devs with macOs systems

2023-10-30 13:43 UTC, SerhiiBorozenets approved these changes

2023-11-03 16:28 UTC, merged