CI-70: Content of the Access Site page is shown incorrect in Gmail/Outlook (not MailTrap)
wahanegi/vibereport pull request #20
Opened 2023-03-16 12:09 UTC by VitaliiShevchenko

[![CI-70](https://badgen.net/badge/JIRA/CI-70/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-70)

[CI-70]: https://cloverpop-internship.atlassian.net/browse/CI-70?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-03-27 10:15 UTC, SokalMet reviewed
as I see - this PR looks the same as here https://github.com/wahanegi/vibereport/pull/23#pullrequestreview-1358787464. I think you do not need to make copies of the same changes. Once prev PR will be done, merge it from master here, and will see then

2023-03-27 11:25 UTC, VitaliiShevchenko commented
Ok. I will be change in the master, and after that make a necessary PR. Thanks

2023-04-09 20:24 UTC, SBorozenets requested changes

2023-04-09 20:24 UTC, SBorozenets commented on app/mailers/user_email_mailer.rb
> +    @link_for_was_not  = [general_link, { last_step: 'results' }].reduce(:merge)
the same

2023-04-09 20:31 UTC, SBorozenets commented
@VitaliiShevchenko it's not the best practice using the magic number in methods, I think we can give up using the method `def calculation(index)` and rewrite code from
```
@table = []
(0..@emotions.length - 1).each { |index| @table.push(@emotions[calculation(index)]) }


def calculation(index)
    (index - (6 * (index / 6).ceil - 1)) * 6 - ((index / 6).ceil - 1) - 2
  end
```
 to smth like this
```
@table = []
@emotions.each_slice(6) { |sliced_emotions| @table << sliced_emotions }
@table = @table.transpose.flatten
```

2023-04-10 11:59 UTC, SokalMet approved these changes

2023-04-10 15:51 UTC, VitaliiShevchenko commented on app/mailers/user_email_mailer.rb
>      @emotions = Emotion.positive.sample(NUMBER_OF_ELEMENTS) +
Excuse me I don't understood what you mean. If you mean variables `@link_for_own_word,  @link_for_was_not and @link_for_emotion ` that variables using by creating email letters in the method `response_invite.html.erb`

2023-04-10 15:54 UTC, VitaliiShevchenko commented on app/mailers/user_email_mailer.rb
>      @user = user
`@user` this variable using to create email letters in the method `response_invite.html.erb`

2023-04-10 16:19 UTC, VitaliiShevchenko commented on app/mailers/user_email_mailer.rb
> +    @link_for_own_word = [general_link, { last_step: 'emotion-entry' }].reduce(:merge)
Thank you very much for this. It looks very nice and better than my)

2023-04-10 17:05 UTC, VitaliiShevchenko commented on app/mailers/user_email_mailer.rb
> +    @link_for_was_not  = [general_link, { last_step: 'results' }].reduce(:merge)
Thanks

2023-04-10 19:23 UTC, SBorozenets commented on app/mailers/user_email_mailer.rb
>      @emotions = Emotion.positive.sample(NUMBER_OF_ELEMENTS) +
@VitaliiShevchenko sorry for misunderstood I wrote about @emotions

2023-04-10 19:39 UTC, SBorozenets commented on app/mailers/user_email_mailer.rb
>      @user = user
I don't see any usage of `@user` in `response_invite.html.erb`, I see that you use it just on row 22 of this file, you can write 
`mail(to: user.email, subject: "Hey #{user.first_name}, how was your week?")`

2023-04-10 21:40 UTC, rogergraves reviewed
I agree with Svitlana, please only declare instance variables if they will be used. Otherwise they take up memory unnecessarily and go against the best practices of OOP.

2023-04-10 21:44 UTC, rogergraves commented on app/mailers/user_email_mailer.rb
> +                     time_period_id: TimePeriod.current, not_working: false, user_id: user.id }
CodeClimate says to align this with the keys of a hash literal

2023-04-10 23:13 UTC, VitaliiShevchenko commented on app/mailers/user_email_mailer.rb
>      @emotions = Emotion.positive.sample(NUMBER_OF_ELEMENTS) +
Ok, thanks for detail explanation)

2023-04-10 23:41 UTC, VitaliiShevchenko commented on app/mailers/user_email_mailer.rb
>      @user = user
I agree with you. Excuse me I mistaked

2023-04-10 23:43 UTC, VitaliiShevchenko commented on app/mailers/user_email_mailer.rb
> +    @link_for_own_word = [general_link, { last_step: 'emotion-entry' }].reduce(:merge)
only must was without @ )))

2023-04-11 07:20 UTC, rogergraves approved these changes
👍🏻

2023-04-11 08:00 UTC, SBorozenets approved these changes

2023-04-11 08:01 UTC, SerhiiBorozenets approved these changes

2023-04-11 09:00 UTC, merged