CІ-122: Style improvements for web pages
wahanegi/vibereport pull request #29
Opened 2023-03-29 16:30 UTC by VitaliiShevchenko

2023-04-04 09:54 UTC, LyubovP approved these changes

2023-04-05 07:47 UTC, SokalMet requested changes

2023-04-05 07:47 UTC, SokalMet commented on app/assets/stylesheets/design_system_vibereport.scss
> +    border:             3px rem solid $royal-blue !important;
remove unneeded rem here

2023-04-05 07:47 UTC, SokalMet commented on app/assets/stylesheets/design_system_vibereport.scss
> +  color:            $white      !important;
you use to-much  "!important" everywhere!

2023-04-06 08:16 UTC, SokalMet approved these changes

2023-04-06 12:24 UTC, merged