CI-42: Emotion Entry
wahanegi/vibereport pull request #38
Opened 2023-04-13 09:07 UTC by Maryna-Harasko

2023-04-13 13:51 UTC, SerhiiBorozenets requested changes

2023-04-13 13:51 UTC, SerhiiBorozenets commented on app/controllers/api/v1/emotions_controller.rb
> +  end
@Maryna-Harasko please define in emotion model scope:
`scope :public, -> { where(public: true) } `
and use it here
```
 Emotion.public.positive.sample(NUMBER_OF_ELEMENTS)
 ...
```

2023-04-14 09:41 UTC, SBorozenets requested changes

2023-04-14 09:41 UTC, SBorozenets commented on app/controllers/api/v1/emotions_controller.rb
> +    @emotion_existed = Emotion.all.find_by(word: params.dig('emotion', 'word'))
@Maryna-Harasko you shouldn`t use instance variable (with @) if it used only in one method.

2023-04-14 09:41 UTC, SBorozenets commented on app/javascript/components/Pages/EmotionEntry.js
> +  };
@Maryna-Harasko for big conditions in js more convenient use switch
https://medium.com/nerd-for-tech/a-case-to-switch-using-switch-statements-in-react-e83e01154f60

2023-04-14 09:43 UTC, SerhiiBorozenets approved these changes

2023-04-14 11:06 UTC, SBorozenets approved these changes

2023-04-14 12:13 UTC, SokalMet commented on app/assets/stylesheets/emition_entry.scss
> +.input__new-word{
I think this class name should look like input-new-word

2023-04-14 12:16 UTC, SokalMet commented on app/assets/stylesheets/emition_entry.scss
> +.emotion-entry__h4{
no point to make difficult class names here. check prev comment

2023-04-14 12:17 UTC, SokalMet commented on app/assets/stylesheets/emition_entry.scss
> +.emotion-entry__h1{
I think this class name should look like emotion-entry with parent tag h1:
h1 {
.emotion-entry {.....}
}

no point to make difficult class names here

2023-04-14 12:21 UTC, SBorozenets approved these changes

2023-04-14 20:34 UTC, SokalMet approved these changes

2023-04-19 08:40 UTC, merged