CI-341: [Sub-Epic] Update Emotion Entry page
wahanegi/vibereport pull request #87
Opened 2023-07-04 08:05 UTC by Maryna-Harasko

https://docs.google.com/document/d/1NdS-pVbDOlFII7C8bDlrrksmFnBqR2kzH2bdFtA1zYI/edit#heading=h.ehtcwiblhdf4

2023-07-04 11:32 UTC, rogergraves approved these changes

2023-07-04 11:33 UTC, rogergraves approved these changes
Please check out the CodeClimate suggestions

2023-07-04 12:20 UTC, SokalMet requested changes

2023-07-05 08:52 UTC, SBorozenets commented on spec/models/emotion_spec.rb
> +      expect(new_word).to be_valid
@Maryna-Harasko you change the meaning of this test, do you still want to check `the capitalized emotion word should not be use`? If yes please add `upcase!`

2023-07-05 08:52 UTC, SBorozenets commented on spec/models/emotion_spec.rb
> +      it 'creates with existing emotion word and category' do
the description of the test not matching with test content. It should be `it 'does not create with existing emotion word and category'`

2023-07-10 21:22 UTC, SBorozenets approved these changes

2023-07-11 10:15 UTC, merged